# Use an official Ubuntu image as a base
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y openssl certbot && \
    rm -rf /var/lib/apt/lists/*

# Copy the certificate generation script
COPY generate_backend_certs.sh /generate_backend_certs.sh

# Create log directory and set permissions
RUN mkdir -p /ssl && mkdir -p /ssl/certs && touch /ssl/cert_generation.log && chmod -R 777 /ssl

# Make the script executable
RUN chmod +x /generate_backend_certs.sh

# Command to run the script
CMD ["/bin/bash", "/generate_backend_certs.sh"]
