# Allow traffic on the external network subnet
pass in proto tcp from 172.19.0.0/16 to any

# Allow traffic on the internal network subnet only from the external network subnet
pass in proto tcp from 172.19.0.0/16 to 172.18.0.0/16 keep state

# Drop all other traffic to the internal network subnet
block in proto tcp from any to 172.18.0.0/16
