scope: postgres_cluster
namespace: /db/
name: postgres_standby

restapi:
  listen: 0.0.0.0:8008
  connect_address: postgres_standby:8008

etcd:
  hosts: etcd:2379

postgresql:
  listen: 0.0.0.0:5432
  connect_address: postgres_standby:5432
  data_dir: /var/lib/postgresql/data
  authentication:
    replication:
      username: replicator
      password: replicatorpass
    superuser:
      username: postgres
      password: ${POSTGRES_PASSWORD}
  parameters:
    max_connections: 100
    shared_buffers: 128MB
    log_min_messages: WARNING
    log_connections: "on"
    log_disconnections: "on"

tags:
  nofailover: false   # Allows this standby to participate in failover
  clonefrom: true     # Marks this node as a candidate for cloning replicas
  nosync: false
