# Use the official PostgreSQL image as the base
FROM postgres:latest

# Install necessary packages and pgBackRest
RUN apt-get update && \
    apt-get install -y pgbackrest && \
    rm -rf /var/lib/apt/lists/*

# Set the entrypoint to bash so the script can be run
ENTRYPOINT ["/bin/bash"]
