apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-cert-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.nginx.cert.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.nginx.cert.tlsKey | b64enc | quote }}
