# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres_primary'
    static_configs:
      - targets: ['postgres_exporter_primary:9187']
  - job_name: 'postgres_standby'
    static_configs:
      - targets: ['postgres_standby:5434']
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'redis-replica'
    static_configs:
      - targets: ['redis-replica:6380']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['es-node-1:9200', 'es-node-2:9200']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
  - job_name: 'minio'
    static_configs:
      - targets: ['minio1:9000', 'minio2:9000']
  - job_name: 'app'
    static_configs:
      - targets: ['app1:8080', 'app2:8080', 'app3:8080']
