version: '3.8'

services:
  consul:
    image: consul:1.11.4
  
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
    volumes:
      - ../../consul/config:/etc/consul.d  # Configuration files
      - consul-data:/consul/data           # Persistent data directory
      - certs-volume:/certs-volume:rw  
      
    networks:
      - internal_network
    command: consul agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui -config-file=/etc/consul.d/consul.hcl
    depends_on:
      - backup
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    build:
      context: ../
      dockerfile: Dockerfile.vault
   
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_API_ADDR=https://vault:8200
      - VAULT_CLUSTER_ADDR=https://vault:8201
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8200:8200"
    volumes:
      - ../../vault/secrets:/vault/secrets
      - ../../vault/config:/vault/config
      - ../../vault/scripts:/vault/scripts
      - vault-data:/vault/file                 # Persistent volume for Vault data
      - certs-volume:/certs-volume:rw          # Persistent data directory for Vault

    networks:
      - internal_network
    cap_add:
      - IPC_LOCK
    depends_on:
      - backup
      - consul

    command: vault server -config=/vault/config/vault-config.hcl

  backup:
    image: busybox
  
    volumes:
      - consul-data:/data/consul            # Back up the Consul data volume
      - vault-data:/data/vault              # Back up the Vault data volume
      - ../../backups:/backups  
      - ../../vault/scripts:/vault/scripts                # Local directory to store the backups
    networks:
      - internal_network
    entrypoint: ["/bin/sh", "-c", "/vault/scripts/backup_script.sh"]
    deploy:
      restart_policy:
        condition: on-failure

networks:
  internal_network:
    name: internal_network
    external: true
    ipam:
      config:
        - subnet: 172.22.0.0/16
  external_network:
    name: external_network
    external: true
    ipam:
      config:
        - subnet: 172.23.0.0/16

volumes:
  consul-data:          # Persistent volume for Consul data
  vault-data:           # Persistent volume for Vault data
  certs-volume:
    external: true
  vault-secrets:
    external: true

