version: '3.8'

services:
  postgres_primary:
    image: bitnami/postgresql-repmgr:latest
    user: "1001"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REPMGR_PRIMARY_ROLE=true
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NAME=postgres-primary-1
      - REPMGR_NODE_NETWORK_NAME=postgres_primary
      - REPMGR_PARTNER_NODES=postgres-primary-1,postgres-standby-2
      - REPMGR_PRIMARY_HOST=postgres_primary
      - REPMGR_PASSWORD=${POSTGRES_PASSWORD}
      - VAULT_ADDR=http://vault:8200
    ports:
      - "5434:5432"
    volumes:
      - ../../data/postgres-primary-data:/bitnami/postgresql
      - ../../scripts:/scripts
      - ../../ssl/certs:/etc/ssl/certs
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["/scripts/init_pg.sh"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  postgres_standby:
    image: bitnami/postgresql-repmgr:latest
    user: "1001"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REPMGR_PRIMARY_ROLE=false
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NAME=postgres-standby-2
      - REPMGR_NODE_NETWORK_NAME=postgres_standby
      - REPMGR_PARTNER_NODES=postgres-primary-1,postgres-standby-2
      - REPMGR_PRIMARY_HOST=postgres_primary
      - REPMGR_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ../../data/postgres-standby-data:/bitnami/postgresql
      - ../../scripts:/scripts
      - ../../ssl/certs:/etc/ssl/certs
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["/scripts/init_pg.sh"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  haproxy:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.haproxy
    volumes:
      - ../../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ../../ssl/certs:/etc/ssl/certs
    ports:
      - "5433:5432"
      - "8404:8404"
    depends_on:
      - postgres_primary
      - postgres_standby
    networks:
      - internal_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  redis-master:
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf", "--appendonly", "yes"]
    ports:
      - "6379:6379"  # Expose Redis on the default port
    volumes:
      - redis-master-data:/data
      - ../../config/redis.conf:/etc/redis/redis.conf
      - ../../ssl/certs:/etc/ssl/certs
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "--tls", "--cert", "/etc/ssl/certs/redis.crt", "--key", "/etc/ssl/certs/redis.key", "--cacert", "/etc/ssl/certs/ca.crt", "-h", "127.0.0.1", "-p", "6379", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  redis-replica:
    image: redis:latest
    command: ["redis-server", "/etc/redis/redis.conf", "--replicaof", "redis-master", "6379"]
    ports:
      - "6380:6379"  # Expose the replica on a different port if needed
    volumes:
      - redis-replica-data:/data
      - ../../config/redis.conf:/etc/redis/redis.conf
      - ../../ssl/certs:/etc/ssl/certs
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "--tls", "--cert", "/etc/ssl/certs/redis.crt", "--key", "/etc/ssl/certs/redis.key", "--cacert", "/etc/ssl/certs/ca.crt", "-h", "127.0.0.1", "-p", "6379", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  internal_network:
    driver: bridge

volumes:
  redis-master-data:
    driver: local
  redis-replica-data:
    driver: local
  es-data-node1:
    driver: local
  es-data-node2:
    driver: local
  es-backup:
    driver: local
  rabbitmq-data-node1:
    driver: local
  rabbitmq-data-node2:
    driver: local
  minio-data1:
    driver: local
  minio-data2:
    driver: local
