version: '3.8'

services:
  postgres_primary:
    image: bitnami/postgresql:15
    container_name: postgres_primary
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: your_actual_password
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: replsecurepassword
      POSTGRESQL_DATABASE: your_postgres_db
      POSTGRESQL_ENABLE_SSL: "true"
      POSTGRESQL_SSL_CERT_FILE: /certs-volume/postgres.crt
      POSTGRESQL_SSL_KEY_FILE: /certs-volume/postgres.key

    ports:
      - "5432:5432"
    networks:
      - internal_network
    volumes:
      - primary_data:/bitnami/postgresql
      - certs-volume:/certs-volume:rw
      - ../../pgpool/config/postgresql.conf:/bitnami/postgresql/conf/postgresql.conf:ro
      - ../../db-backup:/pgbackrest_repo
      - ../../pgpool/config/custom_pg_hba.conf:/opt/bitnami/postgresql/pg_hba.conf:ro
      - ../../pgpool/scripts/create_replication_slot_1.sh:/docker-entrypoint-initdb.d/create_replication_slot.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_replica:
    image: bitnami/postgresql:15
    container_name: postgres_replica
  
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres_primary
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: replsecurepassword
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: your_actual_password
      POSTGRESQL_DATABASE: your_postgres_db
      POSTGRESQL_ENABLE_SSL: "true"
      POSTGRESQL_SSL_CERT_FILE: /certs-volume/postgres.crt
      POSTGRESQL_SSL_KEY_FILE: /certs-volume/postgres.key

    ports:
      - "5433:5432"
    depends_on:
      - postgres_primary
    networks:
      - internal_network
    volumes:
      - replica_data:/bitnami/postgresql
      - certs-volume:/certs-volume:rw
      - ../../pgpool/config/postgresql.conf:/bitnami/postgresql/conf/postgresql.conf:ro
      - ../../pgpool/config/custom_pg_hba.conf:/opt/bitnami/postgresql/pg_hba.conf:ro
      - ../../pgpool/scripts/create_replication_slot_2.sh:/docker-entrypoint-initdb.d/create_replication_slot.sh:ro
 
  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    restart: always
    environment:
      PGPOOL_BACKEND_NODES: "0:postgres_primary:5432,1:postgres_replica:5432"
      PGPOOL_SR_CHECK_USER: "postgres"
      PGPOOL_LISTEN_ADDRESSES: "*"
      PGPOOL_SR_CHECK_PASSWORD: "your_actual_password"
      PGPOOL_ADMIN_USERNAME: "admin"
      PGPOOL_ADMIN_PASSWORD: "admin_password"
      PGPOOL_POSTGRES_USERNAME: "postgres"
      PGPOOL_POSTGRES_PASSWORD: "your_actual_password"
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_HEALTH_CHECK_PERIOD: "10" # Delay between health checks
      PGPOOL_HEALTH_CHECK_TIMEOUT: "20" # Timeout for health checks
      PGPOOL_HEALTH_CHECK_MAX_RETRIES: "5" # Max retries before marking backend as down
      PGPOOL_LOG_MIN_MESSAGES: "debug5"
      PGPOOL_ENABLE_MD5_AUTHENTICATION: "yes"
      PGPOOL_ENABLE_TLS: yes
      PGPOOL_TLS_CERT_FILE: "/certs-volume/postgres.crt"
      PGPOOL_TLS_KEY_FILE: "/certs-volume/postgres.key"
      BITNAMI_DEBUG: "true"
      
      PGPOOL_USER_HBA_FILE: "/opt/bitnami/pgpool/pg_hba.conf"
      
    volumes:
      - certs-volume:/certs-volume:ro
      - ../../pgpool/pgpool_run:/var/run/pgpool
      - ../../pgpool/config/pool_hba.conf:/opt/bitnami/pgpool/pg_hba.conf:ro
      - ../../pgpool/scripts:/scripts
    networks:
      - internal_network
    ports:
      - "5434:5432" # Pgpool-II listens on this port
    depends_on:
      - postgres_primary
      - postgres_replica
    command:
      - /bin/bash
      - -c
      - |
        echo "postgres:md5$(echo -n 'your_actual_passwordpostgres' | md5sum | awk '{print $1}')" > /opt/bitnami/pgpool/conf/pool_passwd
        echo "root:md5$(echo -n 'testroot' | md5sum | awk '{print $1}')" >> /opt/bitnami/pgpool/conf/pool_passwd
        chmod 600 /opt/bitnami/pgpool/conf/pool_passwd
        /opt/bitnami/scripts/pgpool/entrypoint.sh /opt/bitnami/scripts/pgpool/run.sh

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter_primary
    environment:
      DATA_SOURCE_URI: "postgresql://postgres:your_actual_password@postgres_primary:5432/postgres"
    ports:
      - "9187:9187"

  test_replication:
    image: bitnami/postgresql:15
    container_name: test_replication
    depends_on:
      - postgres_primary
      - postgres_replica
    volumes:
      - ../../pgpool/scripts:/scripts
    networks:
      - internal_network
    environment:
      PGPASSWORD: "your_actual_password"  
    entrypoint: ["/bin/bash", "/scripts/verify_replication_autofailover.sh"]

networks:
  internal_network:
    name: internal_network
    external: true

volumes:
  primary_data:
  replica_data:
  certs-volume:
    external: true
  pgpool_run:
    driver: local
